---
deployment:
  tasks:
    - export DEPLOYPATH=/home/SIZNING_CPANEL_LOGININGIZ
    - /bin/cp -R frontend/dist/* $DEPLOYPATH/public_html/
    - /bin/mkdir -p $DEPLOYPATH/uzbamalaka_backend
    - /bin/cp -R Backend/* $DEPLOYPATH/uzbamalaka_backend/
