# Generated by Django 4.2.28 on 2026-02-10 12:24

import core.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('history', models.TextField(blank=True, verbose_name="Umumiy ma'lumot")),
                ('structure', models.TextField(blank=True, verbose_name='Tuzilma haqida matn')),
                ('structure_image', models.ImageField(blank=True, null=True, upload_to=core.models.generate_unique_filename, verbose_name='Tuzilma rasmi')),
                ('student_notes', models.TextField(blank=True, verbose_name='Tinglovchilar uchun eslatma')),
                ('contact_info', models.TextField(blank=True, verbose_name="Aloqa ma'lumotlari")),
                ('address', models.TextField(blank=True, verbose_name='Manzil')),
            ],
            options={
                'verbose_name': 'Markaz haqida',
                'verbose_name_plural': 'Markaz haqida',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('title', models.CharField(max_length=500, verbose_name='Kurs nomi')),
                ('course_type', models.CharField(choices=[('professional_development', 'Malaka oshirish'), ('retraining', 'Qayta tayyorlash')], default='professional_development', max_length=30, verbose_name='Kurs turi')),
                ('duration', models.CharField(blank=True, max_length=100, verbose_name='Davomiyligi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('title', models.CharField(max_length=500, verbose_name='Hujjat nomi')),
                ('category', models.CharField(choices=[('regulatory', "Me'yoriy hujjatlar"), ('plan', 'Ish rejalari'), ('open_data', "Ochiq ma'lumotlar")], default='open_data', max_length=20, verbose_name='Kategoriya')),
                ('file', models.FileField(upload_to=core.models.generate_unique_filename, verbose_name='Fayl')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Hujjat',
                'verbose_name_plural': 'Hujjatlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='Sarlavha')),
                ('cover_image', models.ImageField(upload_to=core.models.generate_unique_filename, verbose_name='Muqova rasmi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Galereya albomi',
                'verbose_name_plural': 'Galereya',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('year', models.CharField(max_length=10, verbose_name='Yil')),
                ('issue_number', models.CharField(blank=True, max_length=20, verbose_name='Son raqami')),
                ('pdf_file', models.FileField(upload_to=core.models.generate_unique_filename, verbose_name='PDF fayl')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=core.models.generate_unique_filename, verbose_name='Muqova rasmi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Jurnal soni',
                'verbose_name_plural': 'Jurnal sonlari',
                'ordering': ['-year', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('article_rules_text', models.TextField(blank=True, verbose_name='Maqola berish tartibi matni')),
                ('article_rules_pdf', models.FileField(blank=True, null=True, upload_to=core.models.generate_unique_filename, verbose_name='Maqola berish tartibi (PDF)')),
                ('about_journal', models.TextField(blank=True, verbose_name='Jurnal haqida')),
            ],
            options={
                'verbose_name': 'Jurnal sozlamalari',
                'verbose_name_plural': 'Jurnal sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('title', models.CharField(max_length=500, verbose_name='Sarlavha')),
                ('content', models.TextField(verbose_name='Matn')),
                ('is_important', models.BooleanField(default=False, verbose_name='Muhim')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('full_name', models.CharField(max_length=300, verbose_name='F.I.SH')),
                ('position', models.CharField(max_length=200, verbose_name='Lavozimi')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('reception_hours', models.CharField(blank=True, max_length=200, verbose_name='Qabul soatlari')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=core.models.generate_unique_filename, verbose_name='Rasm')),
                ('category', models.CharField(choices=[('leadership', 'Rahbariyat'), ('staff', 'Markaziy apparat')], default='staff', max_length=20, verbose_name='Kategoriya')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Xodim',
                'verbose_name_plural': 'Xodimlar',
                'ordering': ['order', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('professors', models.PositiveIntegerField(default=0, verbose_name='Professorlar soni')),
                ('dotsents', models.PositiveIntegerField(default=0, verbose_name='Dotsentlar soni')),
                ('academics', models.PositiveIntegerField(default=0, verbose_name='Akademiklar soni')),
                ('potential', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Ilmiy salohiyat (%)')),
            ],
            options={
                'verbose_name': 'Statistika',
                'verbose_name_plural': 'Statistika',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('full_name', models.CharField(max_length=300, verbose_name='F.I.SH')),
                ('position', models.CharField(max_length=200, verbose_name='Lavozimi')),
                ('degree', models.CharField(blank=True, max_length=200, verbose_name='Ilmiy darajasi')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Unvoni')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=core.models.generate_unique_filename, verbose_name='Rasm')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': "O'qituvchi",
                'verbose_name_plural': "O'qituvchilar",
                'ordering': ['order', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='YearlyStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('year', models.CharField(max_length=10, unique=True, verbose_name='Yil')),
                ('professional_development_count', models.PositiveIntegerField(default=0, verbose_name='Malaka oshirish soni')),
                ('retraining_count', models.PositiveIntegerField(default=0, verbose_name='Qayta tayyorlash soni')),
            ],
            options={
                'verbose_name': 'Yillik statistika',
                'verbose_name_plural': 'Yillik statistikalar',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('image', models.ImageField(upload_to=core.models.generate_unique_filename, verbose_name='Rasm')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.news', verbose_name='Yangilik')),
            ],
            options={
                'verbose_name': 'Rasm',
                'verbose_name_plural': 'Rasmlar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Listener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('record_type', models.CharField(choices=[('MO', 'Malaka oshirish (MO)'), ('QT', 'Qayta tayyorlash (QT)')], default='MO', max_length=5, verbose_name='Sertifikat turi')),
                ('full_name', models.CharField(max_length=300, verbose_name='F.I.SH')),
                ('workplace', models.CharField(blank=True, max_length=500, verbose_name='Ish joyi')),
                ('course_type', models.CharField(blank=True, max_length=300, verbose_name="Yo'nalish")),
                ('series', models.CharField(max_length=20, verbose_name='Seriya')),
                ('number', models.CharField(max_length=50, verbose_name='Raqam')),
                ('duration', models.CharField(blank=True, max_length=200, verbose_name="O'qish muddati (davri)")),
                ('is_verified', models.BooleanField(default=True, verbose_name='Tasdiqlangan')),
            ],
            options={
                'verbose_name': 'Tinglovchi',
                'verbose_name_plural': 'Tinglovchilar (Sertifikatlar)',
                'ordering': ['-created_at'],
                'unique_together': {('series', 'number')},
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('image', models.ImageField(upload_to=core.models.generate_unique_filename, verbose_name='Rasm')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.galleryitem', verbose_name='Galereya')),
            ],
            options={
                'verbose_name': 'Galereya rasmi',
                'verbose_name_plural': 'Galereya rasmlari',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
