# Generated by Django 5.2.11 on 2026-03-25 03:54

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternationalMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('title', models.CharField(max_length=300, verbose_name='Sarlavha')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('media_type', models.CharField(choices=[('photo', 'Foto'), ('video', 'Video')], default='photo', max_length=20, verbose_name='Media turi')),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.models.generate_unique_filename, verbose_name='Rasm')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube havola')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Xalqaro media',
                'verbose_name_plural': 'Xalqaro media',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InternationalPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('name', models.CharField(max_length=250, verbose_name='Hamkor nomi')),
                ('country', models.CharField(blank=True, max_length=120, verbose_name='Davlat')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('link', models.URLField(blank=True, verbose_name='Havola')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=core.models.generate_unique_filename, verbose_name='Logo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Xalqaro hamkor',
                'verbose_name_plural': 'Xalqaro hamkorlar',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InternationalProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('title', models.CharField(max_length=300, verbose_name='Loyiha nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('partners_text', models.CharField(blank=True, max_length=500, verbose_name='Hamkorlar')),
                ('start_date', models.DateField(verbose_name='Boshlanish sanasi')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Tugash sanasi')),
                ('status', models.CharField(choices=[('ongoing', 'Davom etmoqda'), ('completed', 'Yakunlangan')], default='ongoing', max_length=20, verbose_name='Holati')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Xalqaro loyiha',
                'verbose_name_plural': 'Xalqaro loyihalar',
                'ordering': ['order', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='InternationalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('hero_title', models.CharField(blank=True, max_length=300, verbose_name='Hero sarlavha')),
                ('hero_description', models.TextField(blank=True, verbose_name='Hero tavsif')),
                ('about_text', models.TextField(blank=True, verbose_name="Bo'lim matni")),
            ],
            options={
                'verbose_name': 'Xalqaro aloqalar sozlamasi',
                'verbose_name_plural': 'Xalqaro aloqalar sozlamalari',
            },
        ),
    ]
