# Generated by Django 5.2.11 on 2026-03-25 10:49

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_internationalmedia_internationalpartner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Kategoriya nomi')),
                ('slug', models.SlugField(max_length=180, unique=True, verbose_name='Slug')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Yangilik kategoriyasi',
                'verbose_name_plural': 'Yangilik kategoriyalari',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='internationalpartner',
            name='link',
        ),
        migrations.RemoveField(
            model_name='internationalpartner',
            name='logo',
        ),
        migrations.AddField(
            model_name='internationalpartner',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.generate_unique_filename, verbose_name='Hamkor fotosi'),
        ),
        migrations.AddField(
            model_name='statistics',
            name='total_pedagogs',
            field=models.PositiveIntegerField(default=0, verbose_name='Umumiy pedagoglar soni'),
        ),
        migrations.AlterField(
            model_name='internationalproject',
            name='status',
            field=models.CharField(choices=[('planned', 'Rejalashtirilgan'), ('ongoing', 'Davom etmoqda'), ('completed', 'Yakunlangan')], default='ongoing', max_length=20, verbose_name='Holati'),
        ),
        migrations.CreateModel(
            name='InternationalProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('image', models.ImageField(upload_to=core.models.generate_unique_filename, verbose_name='Rasm')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.internationalproject', verbose_name='Loyiha')),
            ],
            options={
                'verbose_name': 'Loyiha rasmi',
                'verbose_name_plural': 'Loyiha rasmlari',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_items', to='core.newscategory', verbose_name='Kategoriya'),
        ),
    ]
