# Generated by Django 5.2.11 on 2026-03-25 11:15

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_newscategory_remove_internationalpartner_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.generate_unique_filename, verbose_name='Hujjat muqova rasmi'),
        ),
        migrations.AddField(
            model_name='journalsettings',
            name='editorial_address',
            field=models.TextField(blank=True, verbose_name='Tahririyat manzili'),
        ),
        migrations.AddField(
            model_name='journalsettings',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='journalsettings',
            name='facebook',
            field=models.URLField(blank=True, verbose_name='Facebook havola'),
        ),
        migrations.AddField(
            model_name='journalsettings',
            name='instagram',
            field=models.URLField(blank=True, verbose_name='Instagram havola'),
        ),
        migrations.AddField(
            model_name='journalsettings',
            name='phone',
            field=models.CharField(blank=True, max_length=100, verbose_name='Telefon'),
        ),
        migrations.AddField(
            model_name='journalsettings',
            name='telegram_primary',
            field=models.URLField(blank=True, verbose_name='Telegram havola 1'),
        ),
        migrations.AddField(
            model_name='journalsettings',
            name='telegram_secondary',
            field=models.URLField(blank=True, verbose_name='Telegram havola 2'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='biography',
            field=models.TextField(blank=True, verbose_name='Biografiyasi'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='duties',
            field=models.TextField(blank=True, verbose_name='Vazifalari'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Elektron pochta'),
        ),
    ]
