# Generated by Django 5.2.11 on 2026-03-25 11:28

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_document_cover_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtGalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('title', models.CharField(max_length=250, verbose_name='Asar nomi')),
                ('author', models.CharField(max_length=250, verbose_name='Muallif')),
                ('image', models.ImageField(upload_to=core.models.generate_unique_filename, verbose_name='Foto')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Art galereya asari',
                'verbose_name_plural': 'Art galereya',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
