# Generated by Django 5.2.11 on 2026-03-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_artgalleryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='awards',
            field=models.CharField(blank=True, max_length=300, verbose_name='Davlat mukofotlari'),
        ),
    ]
