# Generated by Django 5.2.11 on 2026-03-25 11:55

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_teacher_awards'),
    ]

    operations = [
        migrations.AddField(
            model_name='appcontent',
            name='footer_logo',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.generate_unique_filename, verbose_name='Pastki navbar logotipi'),
        ),
        migrations.AddField(
            model_name='appcontent',
            name='header_logo',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.generate_unique_filename, verbose_name='Yuqori navbar logotipi'),
        ),
        migrations.AddField(
            model_name='appcontent',
            name='hero_video_url',
            field=models.URLField(blank=True, verbose_name='Hero banner video havolasi'),
        ),
        migrations.AddField(
            model_name='appcontent',
            name='map_embed_url',
            field=models.URLField(blank=True, verbose_name='Google xarita havolasi'),
        ),
        migrations.AddField(
            model_name='appcontent',
            name='site_name',
            field=models.CharField(blank=True, max_length=300, verbose_name='Sayt nomi'),
        ),
        migrations.CreateModel(
            name='AppHeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('image', models.ImageField(upload_to=core.models.generate_unique_filename, verbose_name='Hero banner rasmi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_images', to='core.appcontent', verbose_name='Kontent')),
            ],
            options={
                'verbose_name': 'Hero banner rasmi',
                'verbose_name_plural': 'Hero banner rasmlari',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
