# Generated by Django 5.2.11 on 2026-03-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_appcontent_footer_logo_appcontent_header_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('full_name', models.CharField(max_length=300, verbose_name='Murojaatchi F.I.SH')),
                ('appeal_type', models.CharField(choices=[('murojaat', 'Murojaat'), ('shikoyat', 'Shikoyat'), ('taklif', 'Taklif')], max_length=20, verbose_name='Murojaat turi')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon raqami')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Elektron pochta')),
                ('telegram_link', models.URLField(blank=True, verbose_name='Telegram link')),
            ],
            options={
                'verbose_name': 'Murojaat',
                'verbose_name_plural': 'Murojaatlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('full_name', models.CharField(max_length=300, verbose_name='F.I.SH')),
                ('application_type', models.CharField(choices=[('professional_development', 'Malaka oshirish'), ('retraining', 'Qayta tayyorlash')], max_length=40, verbose_name='Ariza turi')),
                ('workplace', models.CharField(max_length=500, verbose_name='Asosiy ish joyi')),
                ('direction', models.CharField(max_length=300, verbose_name="Yo'nalish")),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon raqami')),
                ('telegram_link', models.URLField(blank=True, verbose_name='Telegram link')),
            ],
            options={
                'verbose_name': 'Ariza',
                'verbose_name_plural': 'Arizalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
