# Generated by Django 5.2.11 on 2026-03-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_appeal_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('regulatory', "Me'yoriy hujjatlar"), ('plan', 'Ish rejalari'), ('open_data', "Ochiq ma'lumotlar"), ('library', 'Kutubxona')], default='open_data', max_length=20, verbose_name='Kategoriya'),
        ),
    ]
