# Generated by Django 5.2.2 on 2026-07-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_course_contact_fields_and_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='appcontent',
            name='history_en',
            field=models.TextField(blank=True, default='', verbose_name="Umumiy ma'lumot (EN)"),
        ),
        migrations.AddField(
            model_name='appcontent',
            name='history_ru',
            field=models.TextField(blank=True, default='', verbose_name="Umumiy ma'lumot (RU)"),
        ),
        migrations.AddField(
            model_name='appcontent',
            name='site_name_en',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Sayt nomi (EN)'),
        ),
        migrations.AddField(
            model_name='appcontent',
            name='site_name_ru',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Sayt nomi (RU)'),
        ),
        migrations.AddField(
            model_name='appcontent',
            name='structure_en',
            field=models.TextField(blank=True, default='', verbose_name='Tuzilma haqida matn (EN)'),
        ),
        migrations.AddField(
            model_name='appcontent',
            name='structure_ru',
            field=models.TextField(blank=True, default='', verbose_name='Tuzilma haqida matn (RU)'),
        ),
        migrations.AddField(
            model_name='appcontent',
            name='student_notes_en',
            field=models.TextField(blank=True, default='', verbose_name='Tinglovchilar uchun eslatma (EN)'),
        ),
        migrations.AddField(
            model_name='appcontent',
            name='student_notes_ru',
            field=models.TextField(blank=True, default='', verbose_name='Tinglovchilar uchun eslatma (RU)'),
        ),
        migrations.AddField(
            model_name='artgalleryitem',
            name='description_en',
            field=models.TextField(blank=True, default='', verbose_name='Tavsif (EN)'),
        ),
        migrations.AddField(
            model_name='artgalleryitem',
            name='description_ru',
            field=models.TextField(blank=True, default='', verbose_name='Tavsif (RU)'),
        ),
        migrations.AddField(
            model_name='artgalleryitem',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Asar nomi (EN)'),
        ),
        migrations.AddField(
            model_name='artgalleryitem',
            name='title_ru',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Asar nomi (RU)'),
        ),
        migrations.AddField(
            model_name='course',
            name='description_en',
            field=models.TextField(blank=True, default='', verbose_name='Tavsif (EN)'),
        ),
        migrations.AddField(
            model_name='course',
            name='description_ru',
            field=models.TextField(blank=True, default='', verbose_name='Tavsif (RU)'),
        ),
        migrations.AddField(
            model_name='course',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Kurs nomi (EN)'),
        ),
        migrations.AddField(
            model_name='course',
            name='title_ru',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Kurs nomi (RU)'),
        ),
        migrations.AddField(
            model_name='document',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Hujjat nomi (EN)'),
        ),
        migrations.AddField(
            model_name='document',
            name='title_ru',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Hujjat nomi (RU)'),
        ),
        migrations.AddField(
            model_name='internationalproject',
            name='description_en',
            field=models.TextField(blank=True, default='', verbose_name='Tavsif (EN)'),
        ),
        migrations.AddField(
            model_name='internationalproject',
            name='description_ru',
            field=models.TextField(blank=True, default='', verbose_name='Tavsif (RU)'),
        ),
        migrations.AddField(
            model_name='internationalproject',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Loyiha nomi (EN)'),
        ),
        migrations.AddField(
            model_name='internationalproject',
            name='title_ru',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Loyiha nomi (RU)'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_en',
            field=models.TextField(blank=True, default='', verbose_name='Matn (EN)'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_ru',
            field=models.TextField(blank=True, default='', verbose_name='Matn (RU)'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Sarlavha (EN)'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Sarlavha (RU)'),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Kategoriya nomi (EN)'),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='name_ru',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Kategoriya nomi (RU)'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='biography_en',
            field=models.TextField(blank=True, default='', verbose_name='Biografiyasi (EN)'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='biography_ru',
            field=models.TextField(blank=True, default='', verbose_name='Biografiyasi (RU)'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='duties_en',
            field=models.TextField(blank=True, default='', verbose_name='Vazifalari (EN)'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='duties_ru',
            field=models.TextField(blank=True, default='', verbose_name='Vazifalari (RU)'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='position_en',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Lavozimi (EN)'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='position_ru',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Lavozimi (RU)'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='awards_en',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Davlat mukofotlari (EN)'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='awards_ru',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Davlat mukofotlari (RU)'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='degree_en',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Ilmiy darajasi (EN)'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='degree_ru',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Ilmiy darajasi (RU)'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='position_en',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Lavozimi (EN)'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='position_ru',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Lavozimi (RU)'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Unvoni (EN)'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='title_ru',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Unvoni (RU)'),
        ),
    ]
