# Generated by Django 5.2.16 on 2026-07-21 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_appcontent_history_en_appcontent_history_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internationalsettings',
            name='about_text_en',
            field=models.TextField(blank=True, default='', verbose_name="Bo'lim matni (EN)"),
        ),
        migrations.AddField(
            model_name='internationalsettings',
            name='about_text_ru',
            field=models.TextField(blank=True, default='', verbose_name="Bo'lim matni (RU)"),
        ),
        migrations.AddField(
            model_name='internationalsettings',
            name='hero_description_en',
            field=models.TextField(blank=True, default='', verbose_name='Hero tavsif (EN)'),
        ),
        migrations.AddField(
            model_name='internationalsettings',
            name='hero_description_ru',
            field=models.TextField(blank=True, default='', verbose_name='Hero tavsif (RU)'),
        ),
        migrations.AddField(
            model_name='internationalsettings',
            name='hero_title_en',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Hero sarlavha (EN)'),
        ),
        migrations.AddField(
            model_name='internationalsettings',
            name='hero_title_ru',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Hero sarlavha (RU)'),
        ),
        migrations.AddField(
            model_name='journalsettings',
            name='about_journal_en',
            field=models.TextField(blank=True, default='', verbose_name='Jurnal haqida (EN)'),
        ),
        migrations.AddField(
            model_name='journalsettings',
            name='about_journal_ru',
            field=models.TextField(blank=True, default='', verbose_name='Jurnal haqida (RU)'),
        ),
        migrations.AddField(
            model_name='journalsettings',
            name='article_rules_text_en',
            field=models.TextField(blank=True, default='', verbose_name='Maqola berish tartibi matni (EN)'),
        ),
        migrations.AddField(
            model_name='journalsettings',
            name='article_rules_text_ru',
            field=models.TextField(blank=True, default='', verbose_name='Maqola berish tartibi matni (RU)'),
        ),
    ]
