# Generated by Django 5.2.16 on 2026-07-21 07:15

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_internationalsettings_about_text_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('name', models.CharField(max_length=200, verbose_name="Bo'lim nomi")),
                ('name_ru', models.CharField(blank=True, default='', max_length=200, verbose_name="Bo'lim nomi (RU)")),
                ('name_en', models.CharField(blank=True, default='', max_length=200, verbose_name="Bo'lim nomi (EN)")),
                ('icon_name', models.CharField(blank=True, max_length=50, verbose_name='Ikonka nomi (Frontend uchun)')),
                ('color_classes', models.CharField(blank=True, max_length=100, verbose_name='Rang sinflari (Frontend uchun)')),
                ('description', models.TextField(blank=True, verbose_name="Qisqacha ta'rif")),
                ('description_ru', models.TextField(blank=True, default='', verbose_name="Qisqacha ta'rif (RU)")),
                ('description_en', models.TextField(blank=True, default='', verbose_name="Qisqacha ta'rif (EN)")),
                ('tasks', models.TextField(blank=True, verbose_name='Asosiy vazifalar (har bir qatorda bittadan)')),
                ('tasks_ru', models.TextField(blank=True, default='', verbose_name='Asosiy vazifalar (RU)')),
                ('tasks_en', models.TextField(blank=True, default='', verbose_name='Asosiy vazifalar (EN)')),
                ('detail_text', models.TextField(blank=True, verbose_name="Batafsil ma'lumot (Qilingan ishlar)")),
                ('detail_text_ru', models.TextField(blank=True, default='', verbose_name="Batafsil ma'lumot (RU)")),
                ('detail_text_en', models.TextField(blank=True, default='', verbose_name="Batafsil ma'lumot (EN)")),
                ('detail_image', models.ImageField(blank=True, null=True, upload_to=core.models.generate_unique_filename, verbose_name='Batafsil rasm')),
                ('detail_video_url', models.URLField(blank=True, verbose_name='Video havolasi')),
                ('order', models.IntegerField(default=0, verbose_name='Tartib raqami')),
            ],
            options={
                'verbose_name': "Bo'lim",
                'verbose_name_plural': "Bo'limlar",
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pedagogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('full_name', models.CharField(max_length=200, verbose_name='F.I.Sh')),
                ('full_name_ru', models.CharField(blank=True, default='', max_length=200, verbose_name='F.I.Sh (RU)')),
                ('full_name_en', models.CharField(blank=True, default='', max_length=200, verbose_name='F.I.Sh (EN)')),
                ('bio', models.TextField(blank=True, verbose_name="Biografiya / Qisqacha ma'lumot")),
                ('bio_ru', models.TextField(blank=True, default='', verbose_name='Biografiya (RU)')),
                ('bio_en', models.TextField(blank=True, default='', verbose_name='Biografiya (EN)')),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.models.generate_unique_filename, verbose_name='Rasm')),
                ('order', models.IntegerField(default=0, verbose_name='Tartib raqami')),
            ],
            options={
                'verbose_name': 'Pedagog',
                'verbose_name_plural': 'Pedagoglar',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PedagogueProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('title', models.CharField(max_length=300, verbose_name='Loyiha nomi')),
                ('title_ru', models.CharField(blank=True, default='', max_length=300, verbose_name='Loyiha nomi (RU)')),
                ('title_en', models.CharField(blank=True, default='', max_length=300, verbose_name='Loyiha nomi (EN)')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar soni")),
                ('votes_count', models.PositiveIntegerField(default=0, verbose_name='Ovozlar soni (Like)')),
                ('pedagogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.pedagogue', verbose_name='Pedagog')),
            ],
            options={
                'verbose_name': 'Pedagog loyihasi',
                'verbose_name_plural': 'Pedagog loyihalari',
                'ordering': ['-votes_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PedagogueProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('image', models.ImageField(upload_to=core.models.generate_unique_filename, verbose_name='Rasm')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.pedagogueproject', verbose_name='Loyiha')),
            ],
            options={
                'verbose_name': 'Loyiha rasmi',
                'verbose_name_plural': 'Loyiha rasmlari',
                'ordering': ['created_at'],
            },
        ),
    ]
