# Generated by Django 5.2.16 on 2026-07-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_department_pedagogue_pedagogueproject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='biography',
            field=models.TextField(blank=True, verbose_name='Biografiyasi'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='biography_en',
            field=models.TextField(blank=True, default='', verbose_name='Biografiyasi (EN)'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='biography_ru',
            field=models.TextField(blank=True, default='', verbose_name='Biografiyasi (RU)'),
        ),
    ]
