# Generated by Django 5.2.16 on 2026-07-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_teacher_biography_teacher_biography_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedagogueproject',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Loyiha tavsifi'),
        ),
        migrations.AddField(
            model_name='pedagogueproject',
            name='description_en',
            field=models.TextField(blank=True, default='', verbose_name='Loyiha tavsifi (EN)'),
        ),
        migrations.AddField(
            model_name='pedagogueproject',
            name='description_ru',
            field=models.TextField(blank=True, default='', verbose_name='Loyiha tavsifi (RU)'),
        ),
    ]
