# Generated by Django 5.2.16 on 2026-07-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_pedagogueproject_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='admin_note',
            field=models.TextField(blank=True, verbose_name='Admin izohi / Rezolyutsiya'),
        ),
        migrations.AddField(
            model_name='appeal',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('in_progress', 'Jarayonda'), ('resolved', "Ko'rib chiqildi"), ('rejected', 'Rad etildi')], default='pending', max_length=20, verbose_name='Holati'),
        ),
        migrations.AddField(
            model_name='application',
            name='admin_note',
            field=models.TextField(blank=True, verbose_name='Admin izohi / Rezolyutsiya'),
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('in_progress', 'Jarayonda'), ('resolved', "Ko'rib chiqildi"), ('rejected', 'Rad etildi')], default='pending', max_length=20, verbose_name='Holati'),
        ),
    ]
