# Generated by Django 5.2.16 on 2026-07-28 06:32

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_appeal_admin_note_appeal_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('image', models.ImageField(upload_to=core.models.generate_unique_filename, verbose_name='Rasm')),
                ('order', models.IntegerField(default=0, verbose_name='Tartib raqami')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.department', verbose_name="Bo'lim")),
            ],
            options={
                'verbose_name': "Bo'lim batafsil rasmi",
                'verbose_name_plural': "Bo'lim batafsil rasmlari",
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('task_text', models.TextField(verbose_name='Vazifa matni')),
                ('task_text_ru', models.TextField(blank=True, default='', verbose_name='Vazifa matni (RU)')),
                ('task_text_en', models.TextField(blank=True, default='', verbose_name='Vazifa matni (EN)')),
                ('order', models.IntegerField(default=0, verbose_name='Tartib raqami')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_tasks', to='core.department', verbose_name="Bo'lim")),
            ],
            options={
                'verbose_name': "Bo'lim vazifasi",
                'verbose_name_plural': "Bo'lim vazifalari",
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('video_url', models.URLField(verbose_name='Video havolasi')),
                ('order', models.IntegerField(default=0, verbose_name='Tartib raqami')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='core.department', verbose_name="Bo'lim")),
            ],
            options={
                'verbose_name': "Bo'lim batafsil videosi",
                'verbose_name_plural': "Bo'lim batafsil videolari",
                'ordering': ['order', 'id'],
            },
        ),
    ]
