# Generated by Django 5.2.16 on 2026-07-28 06:53

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_departmentimage_departmenttask_departmentvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, help_text="Bo'lim haqida banner ostida chiqadigan qisqacha ma'lumot.", verbose_name="Qisqacha ta'rif"),
        ),
        migrations.AlterField(
            model_name='department',
            name='description_en',
            field=models.TextField(blank=True, default='', help_text="Inglizcha qisqacha ta'rif.", verbose_name="Qisqacha ta'rif (EN)"),
        ),
        migrations.AlterField(
            model_name='department',
            name='description_ru',
            field=models.TextField(blank=True, default='', help_text="Ruscha qisqacha ta'rif.", verbose_name="Qisqacha ta'rif (RU)"),
        ),
        migrations.AlterField(
            model_name='department',
            name='detail_image',
            field=models.ImageField(blank=True, help_text="Zaxira rasm. Ko'p rasm qo'shish uchun sahifa pastidagi inlinedan foydalaning.", null=True, upload_to=core.models.generate_unique_filename, verbose_name='Batafsil rasm'),
        ),
        migrations.AlterField(
            model_name='department',
            name='detail_text',
            field=models.TextField(blank=True, help_text='DIQQAT: Matndagi sarlavhalarni H3 (Heading 3) yoki Qalin (Bold) formatda yozsangiz, saytda ular chiroyli ochilib-yopiladigan akordeon kartalarga aylanadi.', verbose_name="Batafsil ma'lumot (Qilingan ishlar)"),
        ),
        migrations.AlterField(
            model_name='department',
            name='detail_text_en',
            field=models.TextField(blank=True, default='', help_text="Inglizcha batafsil ma'lumot. H3 yoki Bold sarlavhalar ishlating.", verbose_name="Batafsil ma'lumot (EN)"),
        ),
        migrations.AlterField(
            model_name='department',
            name='detail_text_ru',
            field=models.TextField(blank=True, default='', help_text="Ruscha batafsil ma'lumot. H3 yoki Bold sarlavhalar ishlating.", verbose_name="Batafsil ma'lumot (RU)"),
        ),
        migrations.AlterField(
            model_name='department',
            name='detail_video_url',
            field=models.URLField(blank=True, help_text="Zaxira video link. Ko'p video qo'shish uchun sahifa pastidagi inlinedan foydalaning.", verbose_name='Video havolasi'),
        ),
        migrations.AlterField(
            model_name='department',
            name='order',
            field=models.IntegerField(default=0, help_text="Bo'limlar ro'yxatidagi tartibi.", verbose_name='Tartib raqami'),
        ),
        migrations.AlterField(
            model_name='department',
            name='tasks',
            field=models.TextField(blank=True, help_text="Eski zaxira vazifalar maydoni. Yangisini sahifa pastidagi inlinedan qo'shing.", verbose_name='Asosiy vazifalar (har bir qatorda bittadan)'),
        ),
        migrations.AlterField(
            model_name='department',
            name='tasks_en',
            field=models.TextField(blank=True, default='', help_text='Eski zaxira inglizcha vazifalar.', verbose_name='Asosiy vazifalar (EN)'),
        ),
        migrations.AlterField(
            model_name='department',
            name='tasks_ru',
            field=models.TextField(blank=True, default='', help_text='Eski zaxira ruscha vazifalar.', verbose_name='Asosiy vazifalar (RU)'),
        ),
    ]
