# Generated by Django 5.2.16 on 2026-09-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_department_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departmenttask',
            options={'ordering': ['order', 'id'], 'verbose_name': "Bo'lim batafsil ma'lumoti (Akkordeon)", 'verbose_name_plural': "Bo'lim batafsil ma'lumotlari (Akkordeon)"},
        ),
        migrations.AddField(
            model_name='departmenttask',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='Sarlavha (Akkordeon nomi)'),
        ),
        migrations.AddField(
            model_name='departmenttask',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Sarlavha (EN)'),
        ),
        migrations.AddField(
            model_name='departmenttask',
            name='title_ru',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Sarlavha (RU)'),
        ),
        migrations.AlterField(
            model_name='departmenttask',
            name='task_text',
            field=models.TextField(verbose_name='Vazifa matni (Akkordeon ichi)'),
        ),
    ]
