# Generated by Django 5.2.16 on 2026-09-15 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_departmenttask_options_departmenttask_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departmentimage',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Rasm', 'verbose_name_plural': 'Rasmlar'},
        ),
        migrations.AlterModelOptions(
            name='departmenttask',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Asosiy vazifa', 'verbose_name_plural': 'Asosiy vazifalar'},
        ),
        migrations.AlterModelOptions(
            name='departmentvideo',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Video', 'verbose_name_plural': 'Videolar'},
        ),
        migrations.RemoveField(
            model_name='department',
            name='detail_image',
        ),
        migrations.RemoveField(
            model_name='department',
            name='detail_video_url',
        ),
        migrations.RemoveField(
            model_name='department',
            name='tasks',
        ),
        migrations.RemoveField(
            model_name='department',
            name='tasks_en',
        ),
        migrations.RemoveField(
            model_name='department',
            name='tasks_ru',
        ),
        migrations.AlterField(
            model_name='departmenttask',
            name='task_text',
            field=models.TextField(verbose_name='Vazifa matni'),
        ),
        migrations.AlterField(
            model_name='departmenttask',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='Vazifa sarlavhasi (ixtiyoriy)'),
        ),
    ]
