# Generated by Django 5.2.16 on 2026-09-15 11:13

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_departmentimage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('title', models.CharField(max_length=500, verbose_name='Sarlavha')),
                ('title_ru', models.CharField(blank=True, default='', max_length=500, verbose_name='Sarlavha (RU)')),
                ('title_en', models.CharField(blank=True, default='', max_length=500, verbose_name='Sarlavha (EN)')),
                ('content', models.TextField(verbose_name='Matn')),
                ('content_ru', models.TextField(blank=True, default='', verbose_name='Matn (RU)')),
                ('content_en', models.TextField(blank=True, default='', verbose_name='Matn (EN)')),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.models.generate_unique_filename, verbose_name='Rasm')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Sana')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='core.department', verbose_name="Bo'lim")),
            ],
            options={
                'verbose_name': "Bo'lim posti (Qilingan ish)",
                'verbose_name_plural': "Bo'lim postlari",
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
