# Generated by Django 5.2.16 on 2026-09-16 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_departmentpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentpost',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar soni"),
        ),
        migrations.AddField(
            model_name='news',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar soni"),
        ),
    ]
