# Generated by Django 5.2.16 on 2026-09-18 10:14

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_departmentpost_views_count_news_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentpost',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='Rasm havolasi (Asosiy)'),
        ),
        migrations.AlterField(
            model_name='departmentpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.generate_unique_filename, verbose_name='Rasm (Asosiy)'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='duties',
            field=models.TextField(blank=True, verbose_name='Lavozim vazifasi'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='duties_en',
            field=models.TextField(blank=True, default='', verbose_name='Lavozim vazifasi (EN)'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='duties_ru',
            field=models.TextField(blank=True, default='', verbose_name='Lavozim vazifasi (RU)'),
        ),
        migrations.CreateModel(
            name='DepartmentPostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.models.generate_unique_filename, verbose_name="Rasm (Qo'shimcha)")),
                ('image_url', models.URLField(blank=True, verbose_name="Rasm havolasi (Qo'shimcha)")),
                ('order', models.IntegerField(default=0, verbose_name='Tartib raqami')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.departmentpost', verbose_name='Post')),
            ],
            options={
                'verbose_name': 'Post rasmi',
                'verbose_name_plural': 'Post rasmlari',
                'ordering': ['order', 'id'],
            },
        ),
    ]
