# Generated by Django 5.2.16 on 2026-09-18 10:38

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_departmentpost_image_url_alter_departmentpost_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentpost',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=core.models.generate_unique_filename, verbose_name='Video (Asosiy)'),
        ),
        migrations.AddField(
            model_name='departmentpost',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='Video havolasi (Asosiy)'),
        ),
        migrations.AddField(
            model_name='departmentpostimage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=core.models.generate_unique_filename, verbose_name="Video (Qo'shimcha)"),
        ),
        migrations.AddField(
            model_name='departmentpostimage',
            name='video_url',
            field=models.URLField(blank=True, verbose_name="Video havolasi (Qo'shimcha)"),
        ),
    ]
